# Topic modeling with BERTopic

In [9]:
import sqlite3
import pandas as pd
import numpy as np
from tqdm import tqdm

## Prepare data

In [10]:
db_path = "../data/processed/dblp.db"

conn = sqlite3.connect(db_path)

query = """
SELECT id, title, year, venue, type
FROM papers
WHERE title IS NOT NULL
"""

df = pd.read_sql_query(query, conn)

conn.close()

df.head()

,id,title,year,venue,type
0,series/sapere/Freed13,Practical Introspection as Inspiration for AI.,2011,PT-AI,inproceedings
1,series/sapere/Steiner13,C.S. Peirce and Artificial Intelligence: Histo...,2011,PT-AI,inproceedings
2,series/sapere/Sandberg13,Feasibility of Whole Brain Emulation.,2011,PT-AI,inproceedings
3,series/sapere/BerkeleyR13,Machine Mentality?,2011,PT-AI,inproceedings
4,series/sapere/NasutoB13,Of (Zombie) Mice and Animats.,2011,PT-AI,inproceedings

In [11]:
df_sample = df.sample(n=200000, random_state=42)
docs = df_sample["title"].tolist()

## BERTopic

In [12]:
from bertopic import BERTopic
from bertopic.representation import KeyBERTInspired
from sentence_transformers import SentenceTransformer
from umap import UMAP
from hdbscan import HDBSCAN
from sklearn.feature_extraction.text import CountVectorizer, ENGLISH_STOP_WORDS

### Parameteres

In [13]:
embedding_model = SentenceTransformer("all-MiniLM-L6-v2")

umap_model = UMAP(
    n_neighbors=15,
    n_components=5,
    min_dist = 0.0,
    metric="cosine",
    low_memory=True,
    random_state=42,
)

hdbscan_model = HDBSCAN(
    min_cluster_size=300,
    min_samples=5,
    metric="euclidean",
    cluster_selection_method="eom",
    prediction_data=True,
)

custom_stop = list(ENGLISH_STOP_WORDS) + [
    "based", "using", "novel", "efficient", "approach", "method",
    "paper", "proposed", "new", "via", "toward", "towards", "use",
    "used", "study", "system", "systems",
]

vectorizer_model = CountVectorizer(
    stop_words=custom_stop,
    ngram_range=(1, 2),
    min_df=5,
    max_df=0.9
)

representation_model = KeyBERTInspired()

Loading weights: 100%|██████████| 103/103 [00:00<00:00, 2345.27it/s]

### Train

In [14]:
embeddings = embedding_model.encode(
    docs,
    batch_size=512,
    normalize_embeddings=True,
    show_progress_bar=True,
)
np.save("../results/embeddings.npy", embeddings)

Batches: 100%|██████████| 391/391 [12:23<00:00,  1.90s/it]

In [15]:
topic_model = BERTopic(
    embedding_model=embedding_model,
    vectorizer_model=vectorizer_model,
    umap_model=umap_model,
    hdbscan_model=hdbscan_model,
    representation_model=representation_model,
    top_n_words=10,
    nr_topics=50,
    calculate_probabilities=False,
    verbose=True
)

topics, probs = topic_model.fit_transform(docs, embeddings=embeddings)

2026-04-26 01:35:18,310 - BERTopic - Dimensionality - Fitting the dimensionality reduction algorithm
2026-04-26 01:39:38,490 - BERTopic - Dimensionality - Completed ✓
2026-04-26 01:39:38,494 - BERTopic - Cluster - Start clustering the reduced embeddings
2026-04-26 01:39:51,484 - BERTopic - Cluster - Completed ✓
2026-04-26 01:39:51,484 - BERTopic - Representation - Extracting topics using c-TF-IDF for topic reduction.
2026-04-26 01:39:55,812 - BERTopic - Representation - Completed ✓
2026-04-26 01:39:55,815 - BERTopic - Topic reduction - Reducing number of topics
2026-04-26 01:39:55,953 - BERTopic - Representation - Fine-tuning topics using representation models.
2026-04-26 01:40:05,630 - BERTopic - Representation - Completed ✓
2026-04-26 01:40:05,646 - BERTopic - Topic reduction - Reduced number of topics from 128 to 50

In [16]:
new_topics = topic_model.reduce_outliers(
    docs,
    topics,                     # oryginalne topics z fit_transform
    strategy="embeddings",
    embeddings=embeddings,      # twoje 200k embeddingi numpy
    threshold=0.2,              # cosine similarity – obniż do 0.3 jeśli nadal dużo outlierów
)

topic_model.update_topics(docs, topics=new_topics, vectorizer_model=vectorizer_model)
topic_model.save('../results/bertopic_model')

2026-04-26 01:40:07,121 - BERTopic - WARNING: Using a custom list of topic assignments may lead to errors if topic reduction techniques are used afterwards. Make sure that manually assigning topics is the last step in the pipeline.Note that topic embeddings will also be created through weightedc-TF-IDF embeddings instead of centroid embeddings.
2026-04-26 01:40:11,926 - BERTopic - WARNING: When you use `pickle` to save/load a BERTopic model,please make sure that the environments in which you saveand load the model are **exactly** the same. The version of BERTopic,its dependencies, and python need to remain the same.

### Results

In [17]:
# Topic list
topic_model.get_topic_info()

,Topic,Count,Name,Representation,Representative_Docs
0,-1,720,-1_thermal_cu_cell_magnetic,"[thermal, cu, cell, magnetic, cyberbullying, t...",[Interference Management in Visible Light Comm...
1,0,14285,0_object_segmentation_radar_object detection,"[object, segmentation, radar, object detection...",[Coding Convolutional Neural Networks as Spect...
2,1,12455,1_wireless_mimo_radio_sensor networks,"[wireless, mimo, radio, sensor networks, wirel...",[Energy efficiency resource allocation in down...
3,2,7410,2_education_students_reality_teaching,"[education, students, reality, teaching, stude...","[Live Captions in Virtual Reality (VR)., Spati..."
4,3,7986,3_adversarial_neural networks_visual_generative,"[adversarial, neural networks, visual, generat...",[NaturalBench: Evaluating Vision-Language Mode...
5,4,7614,4_language models_large language_text_sentiment,"[language models, large language, text, sentim...",[JTSG: A joint term-sentiment generator for as...
6,5,6382,5_privacy_secure_encryption_security,"[privacy, secure, encryption, security, authen...",[An improved secure certificateless public-key...
7,6,6146,6_segmentation_images_ct_medical,"[segmentation, images, ct, medical, mri, imagi...",[Diffusion-Based Data Augmentation for Medical...
8,7,7221,7_scheduling_gpu_fpga_storage,"[scheduling, gpu, fpga, storage, cache, hardwa...",[A GPU-Based Parallel Reduction Implementation...
9,8,4852,8_dc_electric_voltage_converter,"[dc, electric, voltage, converter, wind, batte...",[Power Smoothing in MCT System with Supercapac...
10,9,5326,9_graphs_social networks_graph neural_social,"[graphs, social networks, graph neural, social...",[Automorphism group of a graph related to zero...
11,10,4182,10_protein_gene_molecular_drug,"[protein, gene, molecular, drug, expression, c...",[BrainTrap: a database of 3D protein expressio...
12,11,4328,11_health_covid_covid 19_19,"[health, covid, covid 19, 19, clinical, health...",[A Study on People's Mental Health on Twitter ...
13,12,6565,12_matrix_gaussian_rank_tensor,"[matrix, gaussian, rank, tensor, feature selec...",[Graph regularized non-negative matrix factori...
14,13,5268,13_recommendation_ontology_recommender_query,"[recommendation, ontology, recommender, query,...","[Dynamic Social Recommendation., Hybrid Recomm..."
15,14,3689,14_speech_audio_music_speaker,"[speech, audio, music, speaker, speech recogni...",[Speech-Text Based Multi-Modal Training with B...
16,15,4665,15_nonlinear_stability_delay_triggered,"[nonlinear, stability, delay, triggered, conse...",[Memory-Based Event-Triggered Fault-Tolerant C...
17,16,6097,16_business_innovation_social_service,"[business, innovation, social, service, indust...",[The adoption behaviour of information technol...
18,17,3397,17_uav_planning_aerial_path planning,"[uav, planning, aerial, path planning, unmanne...",[UAV Path Planning for Optimal Coverage of Are...
19,18,4050,18_anomaly_anomaly detection_security_intrusion,"[anomaly, anomaly detection, security, intrusi...",[ADPretrain: Advancing Industrial Anomaly Dete...
20,19,4111,19_robot_gait_robotic_tactile,"[robot, gait, robotic, tactile, hand, soft, ha...",[Human Tactile Mechanics and the Design of Hap...
21,20,4981,20_code_requirements_checking_software enginee...,"[code, requirements, checking, software engine...",[Automated Traceability Link Recovery Between ...
22,21,3197,21_fault_fault diagnosis_diagnosis_reliability,"[fault, fault diagnosis, diagnosis, reliabilit...",[Partial Inductance Model of Induction Machine...
23,22,3098,22_face_facial_face recognition_person,"[face, facial, face recognition, person, perso...",[SphereFace Revived: Unifying Hyperspherical F...
24,23,3421,23_cmos_optical_amplifier_analog,"[cmos, optical, amplifier, analog, nm, voltage...",[A 40 Gb/s transimpedance amplifier in 65 nm C...
25,24,3703,24_reinforcement learning_reinforcement_games_...,"[reinforcement learning, reinforcement, games,...",[HEPI: High-reward experience-assisted policy ...
26,25,3432,25_scheduling_supply_supply chain_chain,"[scheduling, supply, supply chain, chain, shop...","[Determining Sources of Uncertainty, Performan..."
27,26,3257,26_codes_decoding_ldpc_polynomials,"[codes, decoding, ldpc, polynomials, polynomia...","[On Grid Codes., Quantum codes from a new cons..."
28,27,3394,27_video_super resolution_super_compression,"[video, super resolution, super, compression, ...",[Enhanced Semantic Extraction and Guidance for...
29,28,3091,28_traffic_driving_road_vehicle,"[traffic, driving, road, vehicle, vehicles, ur...","[Autonomous driving., Traffic Flow Simulation ..."
30,29,3413,29_science_scientific_editorial_citation,"[science, scientific, editorial, citation, aca...",[Editor's Message to Special Issue of Software...
31,30,3476,30_robot_robots_human robot_artificial intelli...,"[robot, robots, human robot, artificial intell...",[Designing social greetings in human robot int...
32,31,3853,31_equations_equation_finite_numerical,"[equations, equation, finite, numerical, eleme...",[A finite-element framework for a mimetic fini...
33,32,3453,32_swarm_objective_evolutionary_multi objective,"[swarm, objective, evolutionary, multi objecti...",[A hybrid Particle Swarm Evolutionary Algorith...
34,33,2991,33_brain_eeg_spiking_spiking neural,"[brain, eeg, spiking, spiking neural, connecti...",[EEG/fNIRS Based Workload Classification Using...
35,34,3351,34_reasoning_automata_argumentation_semantics,"[reasoning, automata, argumentation, semantics...",[Separation logic and logics with team semanti...
36,35,1530,35_quantum_entanglement_classical_key distribu...,"[quantum, entanglement, classical, key distrib...",[Quantum Circuits for the CSIDH: Optimizing Qu...
37,36,1631,36_blockchain_contracts_smart contracts_decent...,"[blockchain, contracts, smart contracts, decen...",[A Survey of Distributed Database Systems base...
38,37,1980,37_time series_forecasting_financial_stock,"[time series, forecasting, financial, stock, m...",[GCformer: An Efficient Solution for Accurate ...
39,38,1747,38_fuzzy_decision making_rough_sets,"[fuzzy, decision making, rough, sets, intuitio...",[Fuzzy number intuitionistic fuzzy prioritized...
40,39,2370,39_localization_indoor_positioning_gnss,"[localization, indoor, positioning, gnss, wire...",[Indoor Localization with WiFi Fingerprinting ...
41,40,2012,40_sensors_fiber_sensing_temperature,"[sensors, fiber, sensing, temperature, optical...",[Optical Fiber Sensors for the Detection of Me...
42,41,1085,41_eacute_uuml_der_und,"[eacute, uuml, der, und, auml, oacute, des, cc...",[KI Fachbereichspolitik und K&uuml;nstliche Ko...
43,42,2409,42_visualization_visual_interactive_analytics,"[visualization, visual, interactive, analytics...","[Information Visualization., ChordLink: A New ..."
44,43,1004,43_federated_federated learning_privacy_privac...,"[federated, federated learning, privacy, priva...",[Effective Heterogeneous Federated Learning vi...
45,44,1361,44_emotion_emotional_affective_emotions,"[emotion, emotional, affective, emotions, spee...",[Emotion recognition using facial and audio fe...
46,45,1019,45_disaster_emergency_evacuation_crisis,"[disaster, emergency, evacuation, crisis, situ...",[Automated emergency paramedical response syst...
47,46,1139,46_causal_counterfactual_causality_inference,"[causal, counterfactual, causality, inference,...","[Learning Independent Causal Mechanisms., Caus..."
48,47,808,47_antenna_band_wideband_terahertz,"[antenna, band, wideband, terahertz, wave, ant...",[Antenna parameterization for effectiveness in...
49,48,1045,48_eye_gaze_eye tracking_visual,"[eye, gaze, eye tracking, visual, attention, h...",[Unsupervised Learning of Eye Gaze Representat...

In [18]:
# Words for specific topic
topic_model.get_topic(5)

[('privacy', np.float64(0.08509300938266251)),
 ('secure', np.float64(0.05810975809507396)),
 ('encryption', np.float64(0.05714904166513591)),
 ('security', np.float64(0.051143712955325805)),
 ('authentication', np.float64(0.04071186317281107)),
 ('key', np.float64(0.03651032491579972)),
 ('privacy preserving', np.float64(0.03343269995398265)),
 ('preserving', np.float64(0.03290673949881768)),
 ('attacks', np.float64(0.028178232789656563)),
 ('private', np.float64(0.026899433287596405))]

In [19]:
# Topic visualization
topic_model.visualize_topics()

In [20]:
# Topic relations
topic_model.visualize_hierarchy()

In [21]:
# Most important words
topic_model.visualize_barchart(top_n_topics=10)

In [22]:
df_sample["topic"] = topics

In [23]:
topics_over_time = topic_model.topics_over_time(
    docs,
    timestamps=df_sample["year"].tolist()
)

topic_model.visualize_topics_over_time(topics_over_time)

16it [00:08,  1.99it/s]

## Topic labeling

In [24]:
import os
import numpy as np
import warnings
warnings.filterwarnings("ignore")

from bertopic import BERTopic
from sentence_transformers import SentenceTransformer
from transformers import pipeline

# ── 1. Ładowanie modelu BERTopic ──────────────────────────────
BERTOPIC_PATH = "../results/bertopic_model"
EMBEDDINGS_PATH = "../results/embeddings.npy"

print("Ładowanie modelu BERTopic...")
embedding_model = SentenceTransformer("all-MiniLM-L6-v2")
topic_model = BERTopic.load(BERTOPIC_PATH, embedding_model=embedding_model)
print("Model BERTopic wczytany.")

# ── 2. Embeddingi ─────────────────────────────────────────────
if os.path.exists(EMBEDDINGS_PATH):
    print("Wczytywanie embeddingów z pliku...")
    embeddings = np.load(EMBEDDINGS_PATH)
    print(f"Embeddingi wczytane: {embeddings.shape}")
else:
    print("Generowanie embeddingów (może potrwać ~10 min)...")
    embeddings = embedding_model.encode(
        df_sample["title"].tolist(),
        batch_size=512,
        normalize_embeddings=True,
        show_progress_bar=True,
    )
    np.save(EMBEDDINGS_PATH, embeddings)
    print("Embeddingi zapisane.")

# ── 3. Przypisanie tematów ────────────────────────────────────
print("Przypisywanie tematów...")
topics, _ = topic_model.transform(
    df_sample["title"].tolist(),
    embeddings=embeddings,
)

new_topics = topic_model.reduce_outliers(
    df_sample["title"].tolist(),
    topics,
    strategy="embeddings",
    embeddings=embeddings,
    threshold=0.3,
)
print(f"Tematów przypisanych: {len(set(new_topics)) - (1 if -1 in new_topics else 0)}")
print(f"Outlierów: {new_topics.count(-1) if isinstance(new_topics, list) else (new_topics == -1).sum()}")

# ── 4. Ładowanie TinyLlama ────────────────────────────────────
TINYLLAMA_PATH = "../results/tinyllama_pipeline"

print("Ładowanie modelu do etykiet...")
if os.path.exists(TINYLLAMA_PATH):
    generator = pipeline("text-generation", model=TINYLLAMA_PATH, device=-1, do_sample=False)
else:
    generator = pipeline("text-generation", model="TinyLlama/TinyLlama-1.1B-Chat-v1.0", device=-1, do_sample=False)
    generator.save_pretrained(TINYLLAMA_PATH)
print("TinyLlama wczytany.")

# ── 5. Generowanie etykiet ────────────────────────────────────
def generate_label(topic_id):
    if topic_id == -1:
        return "Outliers"
    
    keywords = [w for w, _ in topic_model.get_topic(topic_id)[:8]]
    keywords_str = ", ".join(keywords)
    
    prompt = f"""<|system|>
You are a computer science researcher. Return only a short topic label (2-4 words), nothing else.</s>
<|user|>
Keywords: {keywords_str}
Label:</s>
<|assistant|>"""
    
    output = generator(
        prompt,
        return_full_text=False,
        max_new_tokens=10,
        pad_token_id=generator.tokenizer.eos_token_id,
    )[0]["generated_text"]
    
    label = output.strip().split("\n")[0].strip().strip('"').strip("'")
    return label if label else "Unknown Topic"

info = topic_model.get_topic_info()
topic_labels = {}

print("Generowanie etykiet dla tematów...")
for _, row in info.iterrows():
    tid = row["Topic"]
    if tid == -1:
        topic_labels[-1] = "Outliers"
        continue
    label = generate_label(tid)
    topic_labels[tid] = label
    print(f"  Topic {tid:3d} ({row['Count']:5,} docs): {label}")

# ── 6. Przypisanie do DataFrame ───────────────────────────────
topic_model.set_topic_labels(topic_labels)

df_sample = df_sample.copy()  # unika SettingWithCopyWarning
df_sample["topic_id"] = new_topics
df_sample["topic_label"] = df_sample["topic_id"].map(topic_labels)

# ── 7. Podgląd ────────────────────────────────────────────────
print("\n── Rozkład tematów ──────────────────────────────────────")
print(df_sample[df_sample["topic_id"] != -1]["topic_label"].value_counts().head(20).to_string())

print("\n── Przykładowe dokumenty ────────────────────────────────")
print(df_sample[df_sample["topic_id"] != -1][["title", "topic_label"]].sample(10).to_string())

Ładowanie modelu BERTopic...

Loading weights: 100%|██████████| 103/103 [00:00<00:00, 3840.84it/s]

Model BERTopic wczytany.
Wczytywanie embeddingów z pliku...
Embeddingi wczytane: (200000, 384)
Przypisywanie tematów...

2026-04-26 01:41:03,704 - BERTopic - Dimensionality - Reducing dimensionality of input embeddings.
2026-04-26 01:41:04,411 - BERTopic - Dimensionality - Completed ✓
2026-04-26 01:41:04,412 - BERTopic - Clustering - Approximating new points with `hdbscan_model`
2026-04-26 01:41:30,726 - BERTopic - Cluster - Completed ✓

Tematów przypisanych: 49
Outlierów: 5759
Ładowanie modelu do etykiet...

Loading weights: 100%|██████████| 201/201 [00:00<00:00, 2337.45it/s]
Writing model shards: 100%|██████████| 1/1 [00:05<00:00,  5.02s/it]
[transformers] Both `max_new_tokens` (=10) and `max_length`(=2048) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

TinyLlama wczytany.
Generowanie etykiet dla tematów...

[transformers] Both `max_new_tokens` (=10) and `max_length`(=2048) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

  Topic   0 (14,285 docs): Keywords: object, segmentation, rad

[transformers] Both `max_new_tokens` (=10) and `max_length`(=2048) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

  Topic   1 (12,455 docs): Keywords: wireless, mimo, radio

[transformers] Both `max_new_tokens` (=10) and `max_length`(=2048) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

  Topic   2 (7,410 docs): Keywords: education, students, reality,

[transformers] Both `max_new_tokens` (=10) and `max_length`(=2048) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

  Topic   3 (7,986 docs): Keywords: adversarial, neural networks,

[transformers] Both `max_new_tokens` (=10) and `max_length`(=2048) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

  Topic   4 (7,614 docs): Keywords: language models, large language,

[transformers] Both `max_new_tokens` (=10) and `max_length`(=2048) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

  Topic   5 (6,382 docs): Keywords: privacy, secure, encryption

[transformers] Both `max_new_tokens` (=10) and `max_length`(=2048) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

  Topic   6 (6,146 docs): Keywords: segmentation, images, c

[transformers] Both `max_new_tokens` (=10) and `max_length`(=2048) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

  Topic   7 (7,221 docs): Keywords: scheduling, gpu,

[transformers] Both `max_new_tokens` (=10) and `max_length`(=2048) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

  Topic   8 (4,852 docs): Keywords: dc, electric, voltage

[transformers] Both `max_new_tokens` (=10) and `max_length`(=2048) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

  Topic   9 (5,326 docs): Keywords: graphs, social networks, graph

[transformers] Both `max_new_tokens` (=10) and `max_length`(=2048) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

  Topic  10 (4,182 docs): Keywords: protein, gene, molecular

[transformers] Both `max_new_tokens` (=10) and `max_length`(=2048) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

  Topic  11 (4,328 docs): Keywords: health, covid, cov

[transformers] Both `max_new_tokens` (=10) and `max_length`(=2048) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

  Topic  12 (6,565 docs): Keywords: matrix, gaussian, rank

[transformers] Both `max_new_tokens` (=10) and `max_length`(=2048) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

  Topic  13 (5,268 docs): Keywords: recommendation, ontology, recomm

[transformers] Both `max_new_tokens` (=10) and `max_length`(=2048) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

  Topic  14 (3,689 docs): Keywords: speech, audio, music,

[transformers] Both `max_new_tokens` (=10) and `max_length`(=2048) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

  Topic  15 (4,665 docs): Keywords: nonlinear, stability, delay

[transformers] Both `max_new_tokens` (=10) and `max_length`(=2048) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

  Topic  16 (6,097 docs): Keywords: business, innovation, social

[transformers] Both `max_new_tokens` (=10) and `max_length`(=2048) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

  Topic  17 (3,397 docs): Keywords: UAV planning, aerial

[transformers] Both `max_new_tokens` (=10) and `max_length`(=2048) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

  Topic  18 (4,050 docs): Keywords: anomaly, anomaly detection

[transformers] Both `max_new_tokens` (=10) and `max_length`(=2048) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

  Topic  19 (4,111 docs): Keywords: robot, gait, robot

[transformers] Both `max_new_tokens` (=10) and `max_length`(=2048) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

  Topic  20 (4,981 docs): Keywords: code, requirements, checking,

[transformers] Both `max_new_tokens` (=10) and `max_length`(=2048) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

  Topic  21 (3,197 docs): Keywords: fault, fault diagnosis,

[transformers] Both `max_new_tokens` (=10) and `max_length`(=2048) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

  Topic  22 (3,098 docs): Keywords: handwriting, handwriting recognition

[transformers] Both `max_new_tokens` (=10) and `max_length`(=2048) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

  Topic  23 (3,421 docs): Keywords: cmos, optical, ampl

[transformers] Both `max_new_tokens` (=10) and `max_length`(=2048) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

  Topic  24 (3,703 docs): Keywords: reinforcement learning, rein

[transformers] Both `max_new_tokens` (=10) and `max_length`(=2048) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

  Topic  25 (3,432 docs): Keywords: scheduling, supply, supply

[transformers] Both `max_new_tokens` (=10) and `max_length`(=2048) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

  Topic  26 (3,257 docs): Keywords: codes, decoding, l

[transformers] Both `max_new_tokens` (=10) and `max_length`(=2048) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

  Topic  27 (3,394 docs): Keywords: video, super resolution, super

[transformers] Both `max_new_tokens` (=10) and `max_length`(=2048) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

  Topic  28 (3,091 docs): Keywords: traffic, driving, road,

[transformers] Both `max_new_tokens` (=10) and `max_length`(=2048) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

  Topic  29 (3,413 docs): Keywords: science, scientific, editorial

[transformers] Both `max_new_tokens` (=10) and `max_length`(=2048) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

  Topic  30 (3,476 docs): Keywords: robot, robots, human

[transformers] Both `max_new_tokens` (=10) and `max_length`(=2048) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

  Topic  31 (3,853 docs): Keywords: equations, equation, finite,

[transformers] Both `max_new_tokens` (=10) and `max_length`(=2048) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

  Topic  32 (3,453 docs): Keywords: swarm, objective, evolution

[transformers] Both `max_new_tokens` (=10) and `max_length`(=2048) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

  Topic  33 (2,991 docs): Keywords: brain, eeg, sp

[transformers] Both `max_new_tokens` (=10) and `max_length`(=2048) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

  Topic  34 (3,351 docs): Keywords: reasoning, automata, argument

[transformers] Both `max_new_tokens` (=10) and `max_length`(=2048) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

  Topic  35 (1,530 docs): Keywords: quantum, entanglement,

[transformers] Both `max_new_tokens` (=10) and `max_length`(=2048) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

  Topic  36 (1,631 docs): Keywords: blockchain, contracts,

[transformers] Both `max_new_tokens` (=10) and `max_length`(=2048) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

  Topic  37 (1,980 docs): Keywords: time series, forecasting

[transformers] Both `max_new_tokens` (=10) and `max_length`(=2048) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

  Topic  38 (1,747 docs): Keywords: fuzzy, decision making

[transformers] Both `max_new_tokens` (=10) and `max_length`(=2048) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

  Topic  39 (2,370 docs): Keywords: localization, indoor,

[transformers] Both `max_new_tokens` (=10) and `max_length`(=2048) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

  Topic  40 (2,012 docs): Keywords: sensors, fiber,

[transformers] Both `max_new_tokens` (=10) and `max_length`(=2048) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

  Topic  41 (1,085 docs): Keywords: eacute, uum

[transformers] Both `max_new_tokens` (=10) and `max_length`(=2048) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

  Topic  42 (2,409 docs): Keywords: visualization, visual, interactive

[transformers] Both `max_new_tokens` (=10) and `max_length`(=2048) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

  Topic  43 (1,004 docs): Keywords: federated, federated learning

[transformers] Both `max_new_tokens` (=10) and `max_length`(=2048) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

  Topic  44 (1,361 docs): Keywords: emotion, emotional,

[transformers] Both `max_new_tokens` (=10) and `max_length`(=2048) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

  Topic  45 (1,019 docs): Keywords: disaster, emergency,

[transformers] Both `max_new_tokens` (=10) and `max_length`(=2048) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

  Topic  46 (1,139 docs): Keywords: causal, counterfactual

[transformers] Both `max_new_tokens` (=10) and `max_length`(=2048) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

  Topic  47 (  808 docs): Keywords: antenna, band, wide
  Topic  48 (1,045 docs): Keywords: eye, gaze, eye

── Rozkład tematów ──────────────────────────────────────
topic_label
Keywords: object, segmentation, rad           14153
Keywords: wireless, mimo, radio               12393
Keywords: adversarial, neural networks,        7954
Keywords: language models, large language,     7548
Keywords: education, students, reality,        7216
Keywords: scheduling, gpu,                     7121
Keywords: matrix, gaussian, rank               6487
Keywords: privacy, secure, encryption          6314
Keywords: segmentation, images, c              6023
Keywords: business, innovation, social         5787
Keywords: graphs, social networks, graph       5208
Keywords: recommendation, ontology, recomm     5208
Keywords: code, requirements, checking,        4913
Keywords: dc, electric, voltage                4735
Keywords: nonlinear, stability, delay          4597
Keywords: health, covid, cov                   4220
Keywords: protein, gene, molecular             4031
Keywords: anomaly, anomaly detection           3988
Keywords: robot, gait, robot                   3920
Keywords: speech, audio, music,                3654

── Przykładowe dokumenty ────────────────────────────────
                                                                                                                                              title                                 topic_label
2830083  Supply chain trust diagnosis (SCTD) using inductive case-based reasoning ensemble (ICBRE): The case of general competence trust diagnosis.        Keywords: scheduling, supply, supply
1477297                                                                                                  Evolution Towards Better AAL Environments.     Keywords: code, requirements, checking,
5880277                                                                            SoK: Large Language Model Copyright Auditing via Fingerprinting.  Keywords: language models, large language,
4093057                                                   Improved Lane Detection With Multilevel Features in Branch Convolutional Neural Networks.           Keywords: traffic, driving, road,
5556358                                                                   Efficient Search-Based Inference for Noisy-OR Belief Networks: TopEpsilon            Keywords: matrix, gaussian, rank
2186498                        A hybrid framework of multiple active appearance models and global registration for 3D prostate segmentation in MRI.           Keywords: segmentation, images, c
5271869                                                                      Learning to Fingerprint the Latent Structure in Question Articulation.  Keywords: language models, large language,
4731415                                                           Domination related parameters in the generalized lexicographic product of graphs.    Keywords: graphs, social networks, graph
2546269                                       Triplet-based Spike Timing Dependent Plasticity Circuit Design for three-terminal Spintronic Synapse.                    Keywords: brain, eeg, sp
1073953                                                                      Implementing Psychological Parameters in a Web-Based Appraisal System.      Keywords: business, innovation, social